### ISSUE TITLE
Assert fails in qos-utils.cc

### ISSUE THREAD

**Issue by mattia-lecci** [signetlabdei/ns3-802.11ad#27]
An assert fails with the following message:
```assert failed. cond="hdr.IsQosData () || packet != 0", file=../src/wifi/model/qos-utils.cc, line=97```
while trying to simulate the following script:
`./waf --run "scratch/evaluate_scheduler_qd_dense_scenario --scheduler=ns3::PeriodicDmgWifiScheduler --logComponentsStr=: --numSTAs=8 --phyMode=DMG_MCS4 --dataRate=100Mbps --mpduAggregation=262143 --simulationTime=15.0 --period=4"`
in the `simulation-develop` branch.

Additional info (quick look at the context with nemiver):
- `packet == 0`
- The problem originates at `mac-low.cc:1949` (function: `void MacLow::BlockAckTimeout (void)`) -> `qos-utils.cc:97` (function: `uint8_t GetTid (Ptr>const Packet> packet, const WifiMacHeader hdr)`).

**Comment by tommyazz** [comment]
[simoutput.txt](https://github.com/signetlabdei/ns3-802.11ad/files/4756887/simoutput.txt)

As can be seen from the output trace above, it seems that the assert is triggered because an SP (of STA 8 probably) starts during the BTI. This SP starts approximately 700 us after the start of the BTI. We should check how the DTI is allocated given these simulation parameters.
